#!/usr/bin/env python3
"""Generate TFT_eSPI VLW smooth font C headers from DejaVuSans-Bold.ttf.

Usage:
  python tools/make_font.py <size_px> <varname> <output_header>

Example:
  python tools/make_font.py 12 DejaVuSansBold12pxData src/fonts/DejaVuSansBold12px.h
  python tools/make_font.py 8  DejaVuSansBold8pxData  src/fonts/DejaVuSansBold8px.h
"""

import struct
import sys
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

CODEPOINTS = sorted(set([
    *range(0x0020, 0x007F),
    *range(0x00A0, 0x0180),
    0x03A9, 0x03C0,
    0x2011, 0x2013, 0x2014,
    0x2018, 0x2019,
    0x201C, 0x201D,
    0x2022, 0x2026,
    *range(0x2070, 0x2080),
    0x20AC,
]))


def make_vlw(size: int) -> bytes:
    import PIL
    pil_ver = tuple(int(x) for x in PIL.__version__.split('.')[:2])
    if pil_ver < (8, 0):
        print(f"Error: Pillow >= 8.0.0 required (found {PIL.__version__})", file=sys.stderr)
        sys.exit(1)
    font = ImageFont.truetype(FONT_PATH, size)
    ascent_px, descent_px = font.getmetrics()
    canvas_h = ascent_px + descent_px + 8
    canvas_w = size * 6

    glyphs = []
    for cp in CODEPOINTS:
        char = chr(cp)

        # Draw at (4, ascent_px + 4) so baseline is at y = ascent_px + 4.
        # Default Pillow anchor places the ascender line at the given y, so
        # baseline = y + ascent_px. Adjust accordingly.
        img = Image.new('L', (canvas_w, canvas_h), 0)
        draw = ImageDraw.Draw(img)
        # anchor='ls': left side of baseline — requires Pillow >= 8.0.0
        draw.text((4, ascent_px + 4), char, font=font, fill=255, anchor='ls')
        baseline_y = ascent_px + 4

        bbox = img.getbbox()
        xadv = round(font.getlength(char))

        if bbox is None:
            # No visible pixels (e.g. space)
            glyphs.append({
                'cp': cp, 'w': 0, 'h': 0,
                'xAdv': xadv if xadv > 0 else (ascent_px + descent_px) // 4,
                'gdX': 0, 'gdY': 0,
                'pixels': b'',
            })
            continue

        x0, y0, x1, y1 = bbox
        w = x1 - x0
        h = y1 - y0
        gdX = x0 - 4         # x offset from cursor (usually 0)
        gdY = baseline_y - y0  # pixels above baseline to top of bitmap

        pixels = bytes(img.crop(bbox).getdata())
        glyphs.append({
            'cp': cp, 'w': w, 'h': h,
            'xAdv': xadv, 'gdX': gdX, 'gdY': gdY,
            'pixels': pixels,
        })

    gcount = len(glyphs)

    # Header: 6 × big-endian uint32
    header = struct.pack('>IIIIII',
        gcount,
        ascent_px + descent_px,  # yAdvance (recalculated at load time anyway)
        ascent_px,
        descent_px,
        0, 0)

    # Glyph table: gcount × 7 × big-endian int32
    glyph_table = b''
    for g in glyphs:
        glyph_table += struct.pack('>IIIIiiI',
            g['cp'],
            g['h'],
            g['w'],
            g['xAdv'],
            g['gdY'],   # signed: positive = above baseline
            g['gdX'],   # signed: usually 0 or small positive
            0)

    bitmap_data = b''.join(g['pixels'] for g in glyphs)
    return header + glyph_table + bitmap_data


def vlw_to_header(vlw: bytes, varname: str, size: int) -> str:
    total = len(vlw)
    lines = [
        f'// Generated by tools/make_font.py from DejaVuSans-Bold.ttf at {size}px',
        f'// {total} bytes VLW smooth font data',
        '',
        f'const uint8_t {varname}[] PROGMEM = {{',
    ]
    row = []
    for i, b in enumerate(vlw):
        row.append(f'0x{b:02X}')
        if len(row) == 16:
            lines.append('  ' + ', '.join(row) + ',')
            row = []
    if row:
        lines.append('  ' + ', '.join(row))
    lines.append('};')
    lines.append(f'const uint32_t {varname}Size = {total};')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    size = int(sys.argv[1])
    varname = sys.argv[2]
    outfile = sys.argv[3]

    vlw = make_vlw(size)
    header = vlw_to_header(vlw, varname, size)
    with open(outfile, 'w') as f:
        f.write(header)
    print(f'Written {len(vlw)} bytes ({len(vlw)//1024}KB) → {outfile}')
